const fs = require('fs').promises;
const path = require('path');

/**
 * Parse .env file into key-value object
 * Preserves comments as metadata but doesn't include in parsed object
 */
async function parseEnvFile(filePath) {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    const parsed = {};
    const lines = content.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }

      // Parse KEY=value or KEY="value" or KEY='value'
      const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
      if (match) {
        const [, key, value] = match;
        // Remove quotes if present
        const cleanValue = value.replace(/^["']|["']$/g, '');
        parsed[key] = cleanValue;
      }
    }

    return parsed;
  } catch (error) {
    if (error.code === 'ENOENT') {
      return {}; // File doesn't exist yet
    }
    throw error;
  }
}

/**
 * Write environment object to .env file
 * Groups variables by category with comments
 */
async function writeEnvFile(filePath, envObject, deploymentType) {
  const lines = [];

  // Header
  lines.push('# ============================================');
  lines.push('# Obsidian Remote Configuration');
  lines.push(`# Generated by Setup Wizard - ${new Date().toISOString()}`);
  lines.push('# ============================================');
  lines.push('');

  // Core Settings
  lines.push('# Core Settings');
  if (envObject.PUID) lines.push(`PUID=${envObject.PUID}`);
  if (envObject.PGID) lines.push(`PGID=${envObject.PGID}`);
  if (envObject.TZ) lines.push(`TZ=${envObject.TZ}`);
  lines.push('');

  // Web Interface
  lines.push('# Web Interface Configuration');
  if (envObject.CUSTOM_PORT) lines.push(`CUSTOM_PORT=${envObject.CUSTOM_PORT}`);
  if (envObject.CUSTOM_HTTPS_PORT) lines.push(`CUSTOM_HTTPS_PORT=${envObject.CUSTOM_HTTPS_PORT}`);
  if (envObject.CUSTOM_USER) lines.push(`CUSTOM_USER=${envObject.CUSTOM_USER}`);
  if (envObject.PASSWORD) lines.push(`PASSWORD=${envObject.PASSWORD}`);
  if (envObject.SUBFOLDER) lines.push(`SUBFOLDER=${envObject.SUBFOLDER}`);
  if (envObject.TITLE) lines.push(`TITLE=${envObject.TITLE}`);
  if (envObject.FM_HOME) lines.push(`FM_HOME=${envObject.FM_HOME}`);
  lines.push('');

  // Production (if applicable)
  if (deploymentType === 'production' || deploymentType === 'production-auth') {
    lines.push('# Production Configuration');
    if (envObject.DOMAIN) lines.push(`DOMAIN=${envObject.DOMAIN}`);
    if (envObject.CADDY_EMAIL) lines.push(`CADDY_EMAIL=${envObject.CADDY_EMAIL}`);
    lines.push('');
  }

  // Authentication (if applicable)
  if (deploymentType === 'production-auth') {
    lines.push('# Authentication Configuration');
    if (envObject.AUTH_OIDC_ISSUER_URL) lines.push(`AUTH_OIDC_ISSUER_URL=${envObject.AUTH_OIDC_ISSUER_URL}`);
    if (envObject.AUTH_PROVIDER_DISPLAY_NAME) lines.push(`AUTH_PROVIDER_DISPLAY_NAME=${envObject.AUTH_PROVIDER_DISPLAY_NAME}`);
    if (envObject.AUTH_REDIRECT_URL) lines.push(`AUTH_REDIRECT_URL=${envObject.AUTH_REDIRECT_URL}`);
    if (envObject.AUTH_CLIENT_ID) lines.push(`AUTH_CLIENT_ID=${envObject.AUTH_CLIENT_ID}`);
    if (envObject.AUTH_CLIENT_SECRET) lines.push(`AUTH_CLIENT_SECRET=${envObject.AUTH_CLIENT_SECRET}`);
    if (envObject.AUTH_COOKIE_SECRET) lines.push(`AUTH_COOKIE_SECRET=${envObject.AUTH_COOKIE_SECRET}`);
    if (envObject.AUTH_COOKIE_SECURE !== undefined) lines.push(`AUTH_COOKIE_SECURE=${envObject.AUTH_COOKIE_SECURE}`);
    if (envObject.AUTH_EMAIL_DOMAINS) lines.push(`AUTH_EMAIL_DOMAINS=${envObject.AUTH_EMAIL_DOMAINS}`);
    if (envObject.AUTH_ALLOWED_USERS) lines.push(`AUTH_ALLOWED_USERS=${envObject.AUTH_ALLOWED_USERS}`);
    lines.push('');
  }

  // Optional Mods
  if (envObject.DOCKER_MODS || envObject.INSTALL_PACKAGES || envObject.KEYBOARD) {
    lines.push('# Optional Docker Mods');
    if (envObject.DOCKER_MODS) lines.push(`DOCKER_MODS=${envObject.DOCKER_MODS}`);
    if (envObject.INSTALL_PACKAGES) lines.push(`INSTALL_PACKAGES=${envObject.INSTALL_PACKAGES}`);
    if (envObject.KEYBOARD) lines.push(`KEYBOARD=${envObject.KEYBOARD}`);
    lines.push('');
  }

  const content = lines.join('\n');
  await fs.writeFile(filePath, content, 'utf-8');
}

/**
 * Load environment template file
 */
async function loadTemplate(templateName) {
  const templates = {
    'local': '.env.example',
    'production': '.env.production.example',
    'auth': '.env.auth.example',
    'sync': '.env.sync.example'
  };

  const templateFile = templates[templateName];
  if (!templateFile) {
    throw new Error(`Unknown template: ${templateName}`);
  }

  const workspaceDir = process.env.WORKSPACE_DIR || '/workspace';
  const filePath = path.join(workspaceDir, templateFile);

  return await parseEnvFile(filePath);
}

module.exports = {
  parseEnvFile,
  writeEnvFile,
  loadTemplate
};
